---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-mail
  namespace: blog
spec:
  encryptedData:
    password: AgA2D0VQF0c4gYroSC7kERXa7oAHc8r2PpKdeyKw7N2wHd6sFPWtKb/6oAU5E9s83j1aXGVSICFlYnFBu2Ob4EI8Ip7Y4PZzgNrQ2whsCBanQUwjwhn4tR8R0tK4Cz9EvNVPLvzrA2dt4JMk6OtVyhf28lOhneCaMsDbzTbbJrQVSe/EsHfNFK1JIhm3NBF9KLlqHNoBbolKS9py5MoRIjq90IfzMioF9NIr29AupBYPUAxskv+5CpPl96Nz7JF3dcTaORMh3FMSj8gfgl+aEuBD6bYgpM0RlY8sZvuamkCBJQ2fm4yi9IrxIhqEjdmBImSvLqDiJ/KRS8YazZVzLL4EDn86eNHksnWCl2s7WAOtMQn0XFPqYcXg864swS40ZziXBuhg4A/QJDByGloVyX3pKbcjnc5RoIzQ8LCW1r/K5+vWbq3wyGhus3IWO5KbXJ6FYs3txjzh0kLcfHPe9WDONgBfcvqWGiniapaYIEB3bqS3AKNsKDm6hgeDpQBdqmxsEt7OMqytdpEFNZz42TOjLhchS8ZUhj86rd41HRcNrefMIl0nOa+wOypTpnLZF4wlvAWTqLpnwmvbQB7mqNYDP7KYEGNPI/zqUUewesZbec+c5fXfYA24lxhCb5F8cxg59Hf14KsAfz1DZ+YHYhrFboMk+tIpZDRUWBOLvaxl2OZl0OzcumgAaQgBGZzcpinvWjZ40yYAS1Ii1j83mGdjBFwkG97TJPNgmAB0p+VywbHZ378zwO50xPWw4E5kBE1pIpHiK+XukeBPCyXD+r7ZC6UA5oYtofH7nFLf8R8iyjrFrNNJ4i7eBjo=
  template:
    metadata:
      name: ghost-mail
      namespace: blog
    type: Opaque
